version: '2'
services:

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=subdomain.example.com
      - LETSENCRYPT_HOST=subdomain.example.com
      - LETSENCRYPT_EMAIL=yourname@subdomain.example.com
#     - VIRTUAL_PORT=8000
      - VIRTUAL_NETWORK=proxy-tier
#    expose:
#      - 8000
    networks:
      - proxy-tier

  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy="true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEBUG=false
    networks:
      - proxy-tier


networks:
  proxy-tier:

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
